#!/usr/bin/env python3
from __future__ import annotations
import argparse,re
from pathlib import Path
import pandas as pd
from bjp_revision_common import *

POS_RE=re.compile(r'(?<!\d)([1-8])(?:x|_)?(\d{2})(?!\d)')

def block(name:str)->str:
    if name.startswith('tm6_'): return 'TM6 opening/geometry'
    if name.startswith('dry_') or name.startswith('r350_'): return 'DRY/ionic lock'
    if name.startswith('pif_') or name.startswith('position_644'): return 'PIF microswitch'
    if name.startswith('w648') or name.startswith('cwxp_'): return 'CWxP microswitch'
    if name.startswith(('y753','n749','npxxy_')): return 'NPxxY/TM7 microswitch'
    if name.startswith('sodium_'): return 'Sodium pocket'
    if name.startswith('tm7_') or name=='tm3_tm7_distance': return 'TM7 geometry'
    if name.startswith('icl2_'): return 'ICL2'
    if name.startswith('tm5_'): return 'TM5 intracellular geometry'
    if name.startswith('h8_'): return 'Helix 8'
    if name.startswith('intracellular_cavity_core_'): return 'Intracellular cavity'
    if name=='activation_consensus_score': return 'Activation summary'
    return 'Other receptor geometry'

def qtype_unit(name:str)->tuple[str,str,str]:
    if name.endswith(('_chi1','_chi2','_angle','_rotation')) or 'mean_phi' in name or 'mean_psi' in name or '_kink' in name:
        return 'angle/dihedral','degrees','Angular geometry computed from receptor coordinates.'
    if name.endswith('_fraction') or name.endswith('_sphericity') or name.endswith('_eccentricity') or name.endswith('_asymmetry') or name.endswith('_alignment'):
        return 'dimensionless','dimensionless','Dimensionless geometric descriptor.'
    if name.endswith('_count') or name.endswith('_longest_helix'):
        return 'count','count','Count of resolved residues/secondary-structure elements.'
    if name.endswith('_volume'): return 'volume','angstrom^3','Geometric cavity/pocket volume.'
    if name.endswith('_area') or name.endswith('_surface_area') or name.endswith('_average_cross_section'):
        return 'area','angstrom^2','Geometric area/cross-section descriptor.'
    if name.endswith('_score'): return 'score','dimensionless','Composite score generated by the project workflow.'
    if any(x in name for x in ('distance','displacement','depth','width','radius','spread','length','centroid_')):
        atom='Minimum heavy-atom distance.' if 'min_distance' in name else 'C-alpha or defined side-chain/centroid distance as implemented in measurement.py.'
        return 'distance/length','angstrom',atom
    return 'numeric geometry','see implementation','Numeric receptor-coordinate descriptor.'

def generic_positions(name:str)->str:
    # Names use compact 350 = 3.50, 634 = 6.34, etc.
    vals=[]
    for m in re.finditer(r'(?<!\d)([1-8])(\d{2})(?!\d)',name): vals.append(f'{m.group(1)}.{m.group(2)}')
    return ';'.join(dict.fromkeys(vals))

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--project-root',type=Path,default=Path.cwd()); ap.add_argument('--outdir',type=Path,default=Path('revision_bjp_2026/D01_feature_dictionary')); args=ap.parse_args()
    root=args.project_root.resolve(); out=args.outdir if args.outdir.is_absolute() else root/args.outdir; out.mkdir(parents=True,exist_ok=True)
    paths=discover_inputs(root); require_paths(paths,['p0_matched']); feats=p0_base_features(paths)
    rows=[]
    for f in feats:
        typ,unit,note=qtype_unit(f)
        rows.append({'feature':f,'block':block(f),'quantity_type':typ,'unit':unit,'generic_positions_in_name':generic_positions(f),'coordinate_definition_summary':note,'missing_value_handling':'Missing structural measurements remain missing; imputation/scaling are fit within training folds for predictive analyses.','used_in_P0_92_feature_matched_set':True})
    tab=pd.DataFrame(rows); write_tsv(tab,out/'matched_92_feature_dictionary.tsv')
    # Make source-code anchors traceable rather than pretending heuristic summaries are the full method.
    src=root/'src/gpcr_icl2/microswitches/measurement.py'
    cav=root/'src/gpcr_icl2/microswitches/cavity.py'
    write_json({'analysis':'D01_feature_dictionary','n_features':len(tab),'source_files':{str(src.relative_to(root)):sha256(src) if src.exists() else None,str(cav.relative_to(root)):sha256(cav) if cav.exists() else None},'note':'This generated dictionary is a machine-readable starting point. Exact atom selections and cavity definitions must be checked against the cited source functions before manuscript freezing.'},out/'manifest.json')

if __name__=='__main__': main()
